### ISSUE TITLE
Flag: United Kingdom is missing white part

### ISSUE THREAD

**Issue by doedje** [toss/tossface#13]
Dear TossFace creators,

I really like your emoji set, it is simply the best!

I discovered a problem with 🇬🇧
The white is actually missing from the image. This works fine on white background, but on black background the white parts become black. It is just transparent.

![image](https://github.com/toss/tossface/assets/3636611/203a6feb-1542-42d7-83a6-8ccbc8b56003)

I hope you can fix this in a future version. Thank you!

**Comment by sudosubin** [comment]
Hello, thank you for using Tossface :)

Thanks to your report, we have confirmed that the background color of 🇬🇧 is transparent.

This issue is scheduled to be resolved in Tossface v1.5 along with other issues and improving Tossface.

Thank you for using Tossface and reporting the issue!
I will come back when Tossface v1.5 is released 😄

**Comment by sudosubin** [comment]
Hello, this issue has been fixed in Tossface [v1.5](https://github.com/toss/tossface/releases/tag/v1.5), and you can use it.

<img src="https://github.com/toss/tossface/assets/32478597/ee1a1228-a6ef-432c-9b40-815d960a9a7b" width="160" />

In addition, if you have any problems using Tossface, please let us know. Thank you for your report 🙇
